vlog axi_agent_pkg.sv
vlog axi_parameter_pkg.sv
vlog axi_interface.sv
vlog axi_footprint_interface.sv
vlog axi_interconnect_veri_top.sv
vlog axi_interconnect_pkg.sv
vlog axi_interconnect_wrapper.sv axi_master_interface_coupler_wrapper.v axi_SI_coupler_wrapper.sv axi_fifo.v axi_fifo_rd.v axi_fifo_wr.v axi_register.v axi_register_rd.v axi_register_wr.v axi_adapter.v axi_adapter_rd.v axi_adapter_wr.v axi_crossbar.v axi_crossbar_addr.v axi_crossbar_rd.v axi_crossbar_wr.v arbiter.v priority_encoder.v
vsim -suppress 12003 -suppress 3053 -logfile log2.txt work.axi_interconnect_top -voptargs=+acc 
add wave -position insertpoint  \
sim:/axi_interconnect_top/u_axi_master_if_0/max_footprint_if/aclk \
sim:/axi_interconnect_top/u_axi_master_if_0/max_footprint_if/aresetn \
sim:/axi_interconnect_top/u_axi_master_if_0/max_footprint_if/awid \
sim:/axi_interconnect_top/u_axi_master_if_0/max_footprint_if/awaddr \
sim:/axi_interconnect_top/u_axi_master_if_0/max_footprint_if/awlen \
sim:/axi_interconnect_top/u_axi_master_if_0/max_footprint_if/awsize \
sim:/axi_interconnect_top/u_axi_master_if_0/max_footprint_if/awburst \
sim:/axi_interconnect_top/u_axi_master_if_0/max_footprint_if/awlock \
sim:/axi_interconnect_top/u_axi_master_if_0/max_footprint_if/awcache \
sim:/axi_interconnect_top/u_axi_master_if_0/max_footprint_if/awprot \
sim:/axi_interconnect_top/u_axi_master_if_0/max_footprint_if/awqos \
sim:/axi_interconnect_top/u_axi_master_if_0/max_footprint_if/awregion \
sim:/axi_interconnect_top/u_axi_master_if_0/max_footprint_if/awuser \
sim:/axi_interconnect_top/u_axi_master_if_0/max_footprint_if/awvalid \
sim:/axi_interconnect_top/u_axi_master_if_0/max_footprint_if/awready \
sim:/axi_interconnect_top/u_axi_master_if_0/max_footprint_if/wdata \
sim:/axi_interconnect_top/u_axi_master_if_0/max_footprint_if/wstrb \
sim:/axi_interconnect_top/u_axi_master_if_0/max_footprint_if/wlast \
sim:/axi_interconnect_top/u_axi_master_if_0/max_footprint_if/wuser \
sim:/axi_interconnect_top/u_axi_master_if_0/max_footprint_if/wvalid \
sim:/axi_interconnect_top/u_axi_master_if_0/max_footprint_if/wready \
sim:/axi_interconnect_top/u_axi_master_if_0/max_footprint_if/bready \
sim:/axi_interconnect_top/u_axi_master_if_0/max_footprint_if/bid \
sim:/axi_interconnect_top/u_axi_master_if_0/max_footprint_if/bresp \
sim:/axi_interconnect_top/u_axi_master_if_0/max_footprint_if/buser \
sim:/axi_interconnect_top/u_axi_master_if_0/max_footprint_if/bvalid \
sim:/axi_interconnect_top/u_axi_master_if_0/max_footprint_if/arid \
sim:/axi_interconnect_top/u_axi_master_if_0/max_footprint_if/araddr \
sim:/axi_interconnect_top/u_axi_master_if_0/max_footprint_if/arlen \
sim:/axi_interconnect_top/u_axi_master_if_0/max_footprint_if/arsize \
sim:/axi_interconnect_top/u_axi_master_if_0/max_footprint_if/arburst \
sim:/axi_interconnect_top/u_axi_master_if_0/max_footprint_if/arlock \
sim:/axi_interconnect_top/u_axi_master_if_0/max_footprint_if/arcache \
sim:/axi_interconnect_top/u_axi_master_if_0/max_footprint_if/arprot \
sim:/axi_interconnect_top/u_axi_master_if_0/max_footprint_if/arqos \
sim:/axi_interconnect_top/u_axi_master_if_0/max_footprint_if/arregion \
sim:/axi_interconnect_top/u_axi_master_if_0/max_footprint_if/aruser \
sim:/axi_interconnect_top/u_axi_master_if_0/max_footprint_if/arvalid \
sim:/axi_interconnect_top/u_axi_master_if_0/max_footprint_if/arready \
sim:/axi_interconnect_top/u_axi_master_if_0/max_footprint_if/rready \
sim:/axi_interconnect_top/u_axi_master_if_0/max_footprint_if/rid \
sim:/axi_interconnect_top/u_axi_master_if_0/max_footprint_if/rdata \
sim:/axi_interconnect_top/u_axi_master_if_0/max_footprint_if/rresp \
sim:/axi_interconnect_top/u_axi_master_if_0/max_footprint_if/rlast \
sim:/axi_interconnect_top/u_axi_master_if_0/max_footprint_if/ruser \
sim:/axi_interconnect_top/u_axi_master_if_0/max_footprint_if/rvalid \
sim:/axi_interconnect_top/u_axi_master_if_0/max_footprint_if/csysreq \
sim:/axi_interconnect_top/u_axi_master_if_0/max_footprint_if/csysack \
sim:/axi_interconnect_top/u_axi_master_if_0/max_footprint_if/cactive \
sim:/axi_interconnect_top/u_axi_master_if_0/max_footprint_if/dbg_if_type
add wave -position insertpoint  \
sim:/axi_interconnect_top/u_axi_slave_if_0/max_footprint_if/aclk \
sim:/axi_interconnect_top/u_axi_slave_if_0/max_footprint_if/aresetn \
sim:/axi_interconnect_top/u_axi_slave_if_0/max_footprint_if/awid \
sim:/axi_interconnect_top/u_axi_slave_if_0/max_footprint_if/awaddr \
sim:/axi_interconnect_top/u_axi_slave_if_0/max_footprint_if/awlen \
sim:/axi_interconnect_top/u_axi_slave_if_0/max_footprint_if/awsize \
sim:/axi_interconnect_top/u_axi_slave_if_0/max_footprint_if/awburst \
sim:/axi_interconnect_top/u_axi_slave_if_0/max_footprint_if/awlock \
sim:/axi_interconnect_top/u_axi_slave_if_0/max_footprint_if/awcache \
sim:/axi_interconnect_top/u_axi_slave_if_0/max_footprint_if/awprot \
sim:/axi_interconnect_top/u_axi_slave_if_0/max_footprint_if/awqos \
sim:/axi_interconnect_top/u_axi_slave_if_0/max_footprint_if/awregion \
sim:/axi_interconnect_top/u_axi_slave_if_0/max_footprint_if/awuser \
sim:/axi_interconnect_top/u_axi_slave_if_0/max_footprint_if/awvalid \
sim:/axi_interconnect_top/u_axi_slave_if_0/max_footprint_if/awready \
sim:/axi_interconnect_top/u_axi_slave_if_0/max_footprint_if/wdata \
sim:/axi_interconnect_top/u_axi_slave_if_0/max_footprint_if/wstrb \
sim:/axi_interconnect_top/u_axi_slave_if_0/max_footprint_if/wlast \
sim:/axi_interconnect_top/u_axi_slave_if_0/max_footprint_if/wuser \
sim:/axi_interconnect_top/u_axi_slave_if_0/max_footprint_if/wvalid \
sim:/axi_interconnect_top/u_axi_slave_if_0/max_footprint_if/wready \
sim:/axi_interconnect_top/u_axi_slave_if_0/max_footprint_if/bready \
sim:/axi_interconnect_top/u_axi_slave_if_0/max_footprint_if/bid \
sim:/axi_interconnect_top/u_axi_slave_if_0/max_footprint_if/bresp \
sim:/axi_interconnect_top/u_axi_slave_if_0/max_footprint_if/buser \
sim:/axi_interconnect_top/u_axi_slave_if_0/max_footprint_if/bvalid \
sim:/axi_interconnect_top/u_axi_slave_if_0/max_footprint_if/arid \
sim:/axi_interconnect_top/u_axi_slave_if_0/max_footprint_if/araddr \
sim:/axi_interconnect_top/u_axi_slave_if_0/max_footprint_if/arlen \
sim:/axi_interconnect_top/u_axi_slave_if_0/max_footprint_if/arsize \
sim:/axi_interconnect_top/u_axi_slave_if_0/max_footprint_if/arburst \
sim:/axi_interconnect_top/u_axi_slave_if_0/max_footprint_if/arlock \
sim:/axi_interconnect_top/u_axi_slave_if_0/max_footprint_if/arcache \
sim:/axi_interconnect_top/u_axi_slave_if_0/max_footprint_if/arprot \
sim:/axi_interconnect_top/u_axi_slave_if_0/max_footprint_if/arqos \
sim:/axi_interconnect_top/u_axi_slave_if_0/max_footprint_if/arregion \
sim:/axi_interconnect_top/u_axi_slave_if_0/max_footprint_if/aruser \
sim:/axi_interconnect_top/u_axi_slave_if_0/max_footprint_if/arvalid \
sim:/axi_interconnect_top/u_axi_slave_if_0/max_footprint_if/arready \
sim:/axi_interconnect_top/u_axi_slave_if_0/max_footprint_if/rready \
sim:/axi_interconnect_top/u_axi_slave_if_0/max_footprint_if/rid \
sim:/axi_interconnect_top/u_axi_slave_if_0/max_footprint_if/rdata \
sim:/axi_interconnect_top/u_axi_slave_if_0/max_footprint_if/rresp \
sim:/axi_interconnect_top/u_axi_slave_if_0/max_footprint_if/rlast \
sim:/axi_interconnect_top/u_axi_slave_if_0/max_footprint_if/ruser \
sim:/axi_interconnect_top/u_axi_slave_if_0/max_footprint_if/rvalid \
sim:/axi_interconnect_top/u_axi_slave_if_0/max_footprint_if/csysreq \
sim:/axi_interconnect_top/u_axi_slave_if_0/max_footprint_if/csysack \
sim:/axi_interconnect_top/u_axi_slave_if_0/max_footprint_if/cactive \
sim:/axi_interconnect_top/u_axi_slave_if_0/max_footprint_if/dbg_if_type

run -all

